version: "2.3"

services:
  zookeeper:
    image: 'zookeeper:3.7'
    restart: "always"
    volumes:
      - 'zookeeper-datalog:/datalog'
      - 'zookeeper-data:/data'

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: "always"
    volumes:
     - 'kafka-data:/bitnami/kafka'

  scylladb:
    image: scylladb/scylla
    environment:
      - CQLSH_HOST=scylladb
    command: --developer-mode=1
    ports:
      - '9042:9042'
    volumes:
      - scylladb:/var/lib/scylla

volumes:
  zookeeper-datalog:
  zookeeper-data:
  kafka-data:
  scylladb:
