[tool.poetry]
name = "saksa"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "^0.14.0"
wsproto = "^1.0.0"
python-socketio = "^5.3.0"
orjson = "^3.5.3"
aioredis = {extras = ["hiredis"], version = "^1.3.1"}
confluent-kafka = "^1.7.0"
trio = "^0.19.0"
python-dotenv = "^0.18.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.6b0", allow-prereleases = true}
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
)/
'''
