on:
  pull_request:
    types: [opened, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    - run: poetry install
    - run: yarn install
    - run: make check
