on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    - run: sudo apt install -y librocksdb-dev libsnappy-dev liblz4-dev librdkafka-dev
    - run: poetry install
    - run: yarn install
    - run: git fetch origin ${{ github.base_ref }}
    - run: make check GIT_BASE_REF='origin/${{ github.base_ref }}'
